planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "astar_planner/AstarPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true